CC = g++
OFILES = Ejercicio4.o
CFLAGS = -g
#CFLAGS = -O
HEADERS = 

Ejercicio4: $(OFILES)
	$(CC) $(CFLAGS) -o Ejercicio4 $(OFILES) $(LIBS)

part1: Ejercicio4.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c Ejercicio4.cpp